"""
CSV-backed retriever.

This retriever loads candidate facts directly from a standardized candidates.csv
(e.g., generated by RETA or SJP via the harmonized interface) and translates the
internal integer IDs back to natural language labels using provided maps.
"""
import logging
from typing import Dict, List, Optional
import pandas as pd

from .base import BaseRetriever, Triple

logger = logging.getLogger(__name__)


class CSVRetriever(BaseRetriever):
    """Retriever backed by a pre-computed standardized candidates CSV.

    Args:
        csv_path:        Path to the standardized candidate CSV.
                         Expected columns: head_id, relation_id, tail_id, and optionally score or rank.
        entity_id_map:   Dict mapping natural lang ID (str) -> harmonized integer ID (int).
        id_to_entity:    Dict mapping harmonized integer ID (int) -> natural lang label (str).
        id_to_relation:  Dict mapping harmonized integer ID (int) -> natural lang relation label (str).
    """

    def __init__(
        self,
        csv_path: str,
        entity_id_map: Dict[str, int],
        id_to_entity: Dict[int, str],
        id_to_relation: Dict[int, str]
    ) -> None:
        self.csv_path = csv_path
        self.entity_id_map = entity_id_map
        self.id_to_entity = id_to_entity
        self.id_to_relation = id_to_relation
        
        self.predictions: Dict[int, List[Triple]] = {}
        self._load_csv()

    def _load_csv(self) -> None:
        """Load and parse the CSV into memory, grouping by head_id."""
        logger.info(f"Loading pre-computed candidates from {self.csv_path}...")
        try:
            frame = pd.read_csv(self.csv_path)
        except Exception as e:
            logger.error(f"Failed to load CSV: {e}")
            return
            
        required = {"head_id", "relation_id", "tail_id"}
        if not required.issubset(set(frame.columns)):
            raise ValueError(f"CSV must include {sorted(required)}. Found: {list(frame.columns)}")

        # Sort columns to ensure correct ranking/budget slicing
        has_rank = "rank" in frame.columns and frame["rank"].notna().any()
        has_score = "score" in frame.columns and frame["score"].notna().any()

        if has_rank:
            frame = frame.sort_values(["head_id", "rank"], ascending=[True, True], na_position="last")
        elif has_score:
            frame = frame.sort_values(["head_id", "score"], ascending=[True, False], na_position="last")

        score_col = frame["score"] if "score" in frame.columns else pd.Series([None] * len(frame), index=frame.index)
        
        # Group by head_id and translate directly to Triples using our string vocabularies
        missing_entities = set()
        missing_relations = set()

        for head_id, sub in frame.groupby("head_id", sort=False):
            head_id_int = int(head_id)
            triples = []
            head_str = self.id_to_entity.get(head_id_int)
            
            if not head_str:
                missing_entities.add(head_id_int)
                head_str = f"<Ent:{head_id_int}>"
                
            for r, t, s in zip(sub["relation_id"], sub["tail_id"], score_col.loc[sub.index]):
                r_int, t_int = int(r), int(t)
                rel_str = self.id_to_relation.get(r_int)
                tail_str = self.id_to_entity.get(t_int)
                
                if not rel_str:
                    missing_relations.add(r_int)
                    rel_str = f"<Rel:{r_int}>"
                if not tail_str:
                    missing_entities.add(t_int)
                    tail_str = f"<Ent:{t_int}>"
                
                score_val = float(s) if not pd.isna(s) else None
                triples.append(Triple(head=head_str, relation=rel_str, tail=tail_str, score=score_val))
            
            self.predictions[head_id_int] = triples

        if missing_entities or missing_relations:
            logger.warning(
                f"Missing string mappings for {len(missing_entities)} entities "
                f"and {len(missing_relations)} relations in the vocab dictionaries."
            )
        logger.info(f"Loaded candidates for {len(self.predictions)} entities.")

    def retrieve(self, entity_id: str, budget: int = 10) -> List[Triple]:
        """Fetch candidates for a given topic entity."""
        # Convert QA entity string (e.g. Freebase ID "m.06w2sn5") to int ID
        if entity_id not in self.entity_id_map:
            logger.debug(f"[CSVRetriever] QA entity '{entity_id}' not found in vocabulary mapping.")
            return []
            
        integer_id = self.entity_id_map[entity_id]
        
        # Look up candidates output by the harmonized CSV
        candidates = self.predictions.get(integer_id, [])
        return candidates[:budget]
